### ISSUE TITLE
bugs in scGen tutorial

### ISSUE THREAD

**Issue by yugeji** [scverse/pertpy-tutorials#21]
Currently on pertpy version 0.6.0.

- cell 4: `train.obs["condition"]` raises `KeyError: 'condition'`. You actually want `train.obs["label"] == "stim")`
- similarly, "condition" should be replaced with "label" for the rest of the notebook
- "Let’s remove stimulated CD4T cells from both the training set. This is just for the sake of this notebook, in practice, you do not need to do this step" this is incorrect. You're removing CD4T cells because you want to generalize your stimulated condition to them.
- cell 7 does not work on cpu or non-jax gpu, raising the following:
`RuntimeError: Backend 'cuda' failed to initialize: module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'. Available backends are ['cpu']` 
You need to add the parameter `accelerator='cpu'`
- cell type names have been changed, specifically from "CD4T" to "CD4 T cells"

**Comment by Zethson** [comment]
Thank you!

**Comment by Lilly-May** [comment]
I noticed that there are also bugs in the scGen batch removal tutorial. The tutorial uses the `pt.dt.kang_2018()` dataset, however, in the current version of the dataset, there is no apparent batch effect:
![umap_kang_2018_replicate_cell_type](https://github.com/theislab/pertpy-tutorials/assets/93096564/6cd60869-6e56-4087-83c6-93d9132b0d0a)

Does anyone maybe have an idea for an alternative dataset to use in this tutorial?

**Comment by Zethson** [comment]
Sigh, the kang dataset is apparently already correct @Lilly-May .

You can try a couple from our list. Candidates are:

1. papalexi (rna)
2. haber regions


If neither of those two fit I can have another look myself

**Comment by Lilly-May** [comment]
Thanks @Zethson!
Unfortunately, neither of those two seems to include uncorrected batch effects:

For the papalexi dataset (couldn't find cell types in .obs):
![output2](https://github.com/theislab/pertpy-tutorials/assets/93096564/7dd57dea-6ec7-44aa-b687-a957f29e4b3d)

For the haber_regions dataset:
![output1](https://github.com/theislab/pertpy-tutorials/assets/93096564/2acaf080-37b2-4bc1-a391-fa8342528b92)

Should I check all the other datasets that are already retrievable via the dataloader?

**Comment by Zethson** [comment]
![image](https://github.com/theislab/pertpy-tutorials/assets/21954664/5ac34418-e422-4c18-896e-55db5330ed27)
Uhm, this is from https://pertpy.readthedocs.io/en/latest/tutorials/notebooks/mixscape.html - I'm surprised that your UMAPS for papalexi look like this?

**Comment by Lilly-May** [comment]
Sorry, yep, you're right - I overlooked that the data wasn't preprocessed at all...🙄 Changed the figure above!

However, I still can't find a cell type annotation, I also had a quick look at the corresponding paper.
I could rewrite the tutorial with the papalexi dataset, `batch_key="replicate"`, and without a `labels_key` (right now, `labels_key="cell_type"` is used), but then the visualizations are of course not that nice. Alternatively, maybe `Phase` as labels key?

**Comment by Zethson** [comment]
Let's maybe look at the datasets scgen and cinemaot used in their manuscripts...

**Comment by Lilly-May** [comment]
The easiest solution is probably to use the original dataset with batch effect. Basically, the tutorial we have is a reproduction of [this tutorial](https://scgen.readthedocs.io/en/stable/tutorials/scgen_batch_removal.html) from SCGEN itself.
Hence, we could either upload that dataset as an additional one via pertpy dataloader or we load the data the way it's loaded in the tutorial, just by providing a link:
```
train = sc.read(
    "./tests/data/pancreas.h5ad",
    backup_url="https://www.dropbox.com/s/qj1jlm9w10wmt0u/pancreas.h5ad?dl=1"
)
```
What do you prefer?

**Comment by Zethson** [comment]
Then let's add a new dataloader `kang_2018_raw`. Please ensure that the number of cells is comparable (and higher in the raw version).

We should probably upload it to our own figshare. I'll do this now.

**Comment by Zethson** [comment]
The dropbox h5ad has less cells than our version :(

**Comment by Lilly-May** [comment]
I see.😕  I'll create a first PR for the tutorial "scGen - Perturbation response prediction" then, because that's already fixed. As soon as we have the new dataset with batch effect up, I'll fix the "scgen_batch_removal" tutorial as well but in a separate PR.
