### ISSUE TITLE
Bugs in Distance metrics tutorial

### ISSUE THREAD

**Issue by Lilly-May** [scverse/pertpy-tutorials#22]
In it's current version, the _Distance metrics_ tutorial throws several errors. Most of them can be easily fixed by implementing the following things:
- [x] Remove `verbose` as a parameter from `pairwise` method whenever it's used in the tutorial
- [x] Specify that 'X_pca' is the `obsm_key` parameter when initializing a Distance object (`obsm_key='X_pca'`)
- [x] Use correct distance name: There is one section titled _PseudobulkDistance_ and a Distance object is initialized with the distance 'pseudobulk'. This distance, however, doesn't exist, hence an error is thrown. Is it possible that `pseudobulk` was renamed and is now called `euclidean`?

All those things are easily fixed, I just need conformation on the distance that is supposed to be used in the Pseudobulk section.

**Comment by Zethson** [comment]
@Lilly-May yes, it was indeed renamed to what you said
